name: Continuous

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Enable build
      run: chmod +x ./build.sh

    - name: Run build
      run: >
        ./build.sh --target CompleteBuild --build-version git --build-number $GITHUB_RUN_NUMBER --no-logo

    - name: Collect NuGet for publish
      uses: actions/upload-artifact@v7
      with:
        path: 'artifacts'
        name: 'nuget-packages'

  publish:
    needs: build
    permissions:
      id-token: write
    environment: nuget-push
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: nuget-packages

      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: nugetLogin
        with:
          user: ${{ env.USER }}

      - name: Push to NuGet
        run: dotnet nuget push **/*.nupkg --api-key $NUGET_API_KEY
        env:
          NUGET_API_KEY: ${{ steps.nugetLogin.outputs.NUGET_API_KEY }}
